### ISSUE TITLE
Create a wordpress subfolder for Internethealthreport.org/2018 and give access to Vizzuality devs

### ISSUE THREAD

**Issue by kaodro** [mozilla/internet-health-report#42] opened 2017-10-09 16:47 UTC
Hi @cadecairos , we would like to create a wordpress instance for the upcoming Report so that Vizzuality developers can start getting familiar with it (the coding is about to start in November).

Could you do it and add the following emails with full developer rights:
David.Inga@vizzuality.com (developer)
Clement.Prodhomme@vizzuality.com (developer) 
and
Clara.Linos@vizzuality.com (project manager, regular editor access)

They will be working in an open repository on github.

Let me know if you need any more info or anything is unclear. Thanks!

**Comment by cadecairos** [comment] 2017-10-11 18:15
@kaodro Will the report eventually end up on the main Internet Health Report WordPress instance?

It might make more sense to create a new "site" there and use that. We should be able to secure it from the public during development.

**Comment by kaodro** [comment] 2017-10-11 18:47
You are right, I think we want a subfolder on the same instance, does that make sense to you? Thanks!
We want a new site and we want to secure it from the public during development. The site will have a whole new design and it will be developed by Vizzuality.

**Comment by cadecairos** [comment] 2017-10-11 19:45
@kaodro what subfolder should we use? `/v02`?

**Comment by kaodro** [comment] 2017-10-11 20:34
the url should be Internethealthreport.org/2018 so maybe it makes sense to call the subfolder like that, too (/2018)

**Comment by kaodro** [comment] 2017-10-17 15:47
hey @cadecairos any news here? Do you need more info?

**Comment by cadecairos** [comment] 2017-10-17 16:39
Hi @kaodro -  the one blocker I have is finding a way to password protect just a single site on a multi-site instance. 

If it's not a huge deal, we could easily add the site without a password block , and as long as it's not linked to anywhere on the web, it won't be indexed by web crawlers.

**Comment by kaodro** [comment] 2017-10-18 12:01
@cadecairos sorry if I'm confusing things but would it be an option for them to build on staging, like the previous report, and then transfer it to the proper site once ready? Would that help the password protection issue? Thanks for patience answering all these questions.

**Comment by cadecairos** [comment] 2017-10-18 12:57
We could use staging - but it won't be easy to transfer things over to the production site. Multi-site installs don't work well with staging.

**Comment by kaodro** [comment] 2017-10-18 18:25
@cadecairos I talked with the team and they confirmed my feeling: we need to password protect the site while it's being built. So whether we need to find a solution for the site or create a staging version.

**Comment by cadecairos** [comment] 2017-10-18 21:18
@kaodro so, I've found a plugin for Wordpress that will let us password protect a site on the network. It's going to cost $50 a month to use it though - is that alright? I can cancel it after we launch too, since it's month-to-month.

**Comment by kaodro** [comment] 2017-10-19 11:00
@cadecairos that sounds like an expense we could afford. I will bring in the developer from Vizzuality into this discussion so he can say what he prefers given the risks (staging or this solution). Thanks for checking!

**Comment by davidsingal** [comment] 2017-10-20 15:41
Hi! @cadecairos I've just tested this [plugin](https://es.wordpress.org/plugins/wp-basic-auth/). It adds a basic auth authentication for the site. It should be enough to protect the site. What do you think?

**Comment by cadecairos** [comment] 2017-10-20 16:48
@davidsingal is that plugin compatible with multi-site installs? We don't want to block the landing site or v01 report.

**Comment by davidsingal** [comment] 2017-10-20 18:01
@cadecairos let me check it in a multisite demo page. I will let you know the result.

**Comment by davidsingal** [comment] 2017-10-20 18:17
@cadecairos do you know if we are using apache? I'm thinking we could put basic auth in a specific directory using `.htaccess`. If we are using NGINX, we can add this rule in the config file. What do you think? Could it work?

**Comment by cadecairos** [comment] 2017-10-20 18:43
I'm not sure what WPEngine uses to host WP installs on their infrastructure - but I think there is a `.htaccess` file in the webroot of each WP install, which means they're probably using Apache at some stage.

**Comment by kaodro** [comment] 2017-11-03 11:04
Hello all @cadecairos @davidsingal we need to keep moving forward here - we agreed with Vizzuality that the development of the site will start asap. Do you need any more information to set up the site?

**Comment by cadecairos** [comment] 2017-11-03 15:13
@kaodro @davidsingal I dug into this and was able to set up basic auth for a new subsite.

https://internethealthreport.org/2018/ is ready for development.

In order to grant access, I'll need a list of users to generate passwords for, and we'll need a end-to-end encrypted means of transferring the credentials. I'm open to using something like Signal or Telegram.

**Comment by kaodro** [comment] 2017-11-06 11:17
Fantastic, thank you!
I will send you an email with a list, phone numbers and preferred channel of encrypted communication (Signal/Telegram (mind you, it is not encrypted by default but I'm sure you know it?)/do you use Wire?).  Thanks, again.

**Comment by santostiago** [comment] 2017-12-01 15:15
Hi @cadecairos. I was trying to set up the WP site but I don't seem to have access to do it.
The credentials you sent me allow me to view the current website in WP, but not to access the admin console nor to upload the files needed to set up the backoffice.
Can you please give me permissions to do that or suggest another way to do it? 
Thank you

**Comment by kaodro** [comment] 2017-12-05 14:01
@cadecairos can you help Tiago? Vizzuality needs to start the work asap. Thanks for clarifying this issue so they can move forward

**Comment by santostiago** [comment] 2017-12-13 10:10
Hi @cadecairos I've managed to log in into the wp-admin after you gave me permissions to do so, but I still lack permissions to install plugins and to upload themes. Could you please give me permissions to do so?
Thank you

**Comment by cadecairos** [comment] 2017-12-13 13:55
@santostiago I've granted you permissions that will let you install plugins and themes via the "network" admin dashboard. From there you'll be able to enable them on the 2018 sub site.

**Comment by santostiago** [comment] 2017-12-13 14:38
@cadecairos ok, thank you. I'm going to test it now!

**Comment by santostiago** [comment] 2017-12-13 15:45
@cadecairos it's working perfectly. Thank you.

**Comment by dhakelila** [comment] 2018-01-25 13:45
Hi @cadecairos, I'm Clara, from Vizzuality. 
We'd need to install a plugin on the new Internet Health Report 2018 and it seems we don't have permissions for that. 

Could you give me access or install this plugin for me, please? 
https://wordpress.org/plugins/tinymce-advanced/

If you install it, let me know as I need to do a very quick configuration as well. 
Or if you prefer to do it yourself, it is just going to the Advance Settings panel of the pluging and un-check the option for automatic removal of <p> and <br/> tags.

**Comment by dhakelila** [comment] 2018-01-25 14:08
Hi @cadecairos, ignore my previous message. I reached Tiago and he told me how to do it. 
I was looking at the wrong place. 

Not used to multisite configurations!

**Comment by cadecairos** [comment] 2018-01-25 14:38
Glad you've got it sorted out!

**Comment by santostiago** [comment] 2018-01-26 09:23
Hi @cadecairos. We've been experiencing some issues when uploading new versions of the theme, as sometimes the old versions are still being displayed. This happens more often when no new files are added and we just modified some old ones.

When requesting the webpage, the old files are the ones sent. I checked that WP has no active cache plugin for the current project (HTTP Headers is deactivated) but I don't know the setup of the servers (so there might be some caching in the webserver, cloudflare or somewhere else).
Do you know if there's a way we can invalidate the caching of the project's files on uploading them?

Thank you!

**Comment by dhakelila** [comment] 2018-01-29 12:00
Hi @cadecairos, could you have a look at the issue Tiago is flagging? 

The problem is that we can not show progress as the site seems not update when we upload the changes.

**Comment by cadecairos** [comment] 2018-01-29 14:52
Hi, There are multiple levels of caching on the site. I've turned on a setting that should enable Administrators (@kaodro and Solana) to see the WPEngine control panel in WordPress.

@kaodro, you can purge the cached site data using the button labelled "Purge All Caches" which can be found by clicking the "WP Engine" dashboard button, which is shown below:

![](https://screenshotscdn.firefoxusercontent.com/images/5da9cb7b-6e35-4f8a-82a1-4bc3d3e8aca2.png)

I've purged the caches already, but Kasia and Solana should now also be able to purge them to get updates out.

**Comment by kaodro** [comment] 2018-01-29 15:13
thanks, @cadecairos . @dhakelila let me know if it works now and for the future, I will know how to purge the cache, if needed.

**Comment by dhakelila** [comment] 2018-01-29 15:20
Thank you! Those are really good news! 

And btw, changes are working. Maybe I'd add a bit more of space between paragraphs, but is working.

**Comment by santostiago** [comment] 2018-02-09 14:14
Hi @cadecairos! In order to have the talk plugin to work, we need the talk server running and I need to know the url to connect to it. Is that something you can do?
Thank you

**Comment by cadecairos** [comment] 2018-02-10 02:47
@santostiago You can embed this snippet on pages where we want Talk:

```
<div id="coral_talk_stream"></div>
<script src="https://talk.mofoprod.net/static/embed.js" async onload="
  Coral.Talk.render(document.getElementById('coral_talk_stream'), {
    talk: 'https://talk.mofoprod.net/'
  });
"></script>
```

@kaodro who's going to be responsible for administering the conversation? We should get them an account on our Talk instance.

**Comment by kaodro** [comment] 2018-02-12 11:08
@cadecairos it will be me, Solana and a bunch of volunteers we are recruiting now (don't know their names yet). Which information do you need: email and phone numbers + encrypted msg again? thanks!

**Comment by cadecairos** [comment] 2018-02-12 13:39
You should all be able to sign up via the comments form, and I can promote people to moderators internally.

**Comment by santostiago** [comment] 2018-02-19 14:32
@cadecairos Hi Christopher, in order to deactivate the reactions plugin for all sites except for the 2018 one, I'd like to know the id of the 2018 site. (Otherwise, we'd have to install a plugin to manage this, and it's better to avoid it).

**Comment by dhakelila** [comment] 2018-02-21 17:12
Hi @cadecairos, can you take a look at Tiago's comment? We need the id for the 2018 site. 
Thanks!

**Comment by cadecairos** [comment] 2018-02-21 17:45
@santostiago The 2018 sub-site has the id `6`

**Comment by santostiago** [comment] 2018-02-22 11:12
Thank you @cadecairos

**Closed as completed** 2018-10-03 20:08 UTC
